#默认使用配置
hostName: 192.168.2.113:9049
server:
  profiles: dev
  port: 9049
  tomcat:
    uri-encoding: UTF-8
#test
test: 111111111111111111111

#开发配置
spring:
  datasource:
    url: jdbc:mysql://192.168.2.139/gx_call?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  thymeleaf:
    cache: false
  jackson:
    date-format: java.text.SimpleDateFormat
  http:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
      #tomcat临时上传目录
      location: ${file.upload-path}/template
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  redis:
    #数据库索引
    database: 4
    host: 192.168.2.139
    port: 6378
    password: 123456
#    host: 210.21.48.70
#    port: 7936
#    password: infosun123456
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
    timeout: 10000
  main:
    allow-bean-definition-overriding: true
    #文件上传大小控制
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  ## 过期时间12小时
expire-time: 43200000

#远程录音文件前缀
recordFile: http://210.21.48.75:9047/record/

#日志文件
logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
  config: classpath:logback-dev.xml

#录音
callRecord:
  callRecordPath: D://
#用户头像
file:
  upload-path: c://tx/file/
  office-path: d://doc2htmltest/

#Excel模板
ExcelTemplates:
  FilePath: /static/excel/
  tempNames: customTemplates


#License相关配置
license:
  subject: license_demo
  publicAlias: publicCert
  storePass: public_password1234
  licensePath: C:/key/customer/license.lic
  publicKeysStorePath: C:/key/publicCerts.keystore

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      logic-delete-value: -1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)


endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false